### ISSUE TITLE
Unable to start archive Now!  on windows- WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by kanihal** [machawk1/wail#265]
```
Traceback (most recent call last):
  File "<string>", line 138, in archiveNow
  File "<string>", line 263, in startTomcat
  File "C:\Downloads\pyinstaller-2.0\WAIL\build\pyi.win32\WAIL\out00-PYZ.pyz\subprocess", line 679, in __init__
  File "C:\Downloads\pyinstaller-2.0\WAIL\build\pyi.win32\WAIL\out00-PYZ.pyz\subprocess", line 893, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
````
![some](https://user-images.githubusercontent.com/7579686/29488838-c9ba9db2-84c7-11e7-8937-c16d6a855d6d.PNG)

Am I missing something?

**Comment by machawk1** [comment]
Thanks for the report, @kanihal. The Windows version of this codebase is not actively maintained, as I currently do not have a Windows machine on which to test. For replication, what version of Windows are you using?

**Comment by kanihal** [comment]
@machawk1 I am using window 10 edu license

**Comment by machawk1** [comment]
@milliem-3923 Thanks for the update. Are you using the binary/released version of WAIL or building from source? I think this issue _should_ be resolved in a fresh build but I have yet to get the Windows version to the quality I think it needs to mint a new release.

**Comment by milliem-3923** [comment]
Thanks for the swift reply. 

I'm using the released version that I got here:[http://machawk1.github.io/wail/#download](url). I'm an amateur so I don't really have any flexibility when it comes to building from source or what not. I look forward to the upcoming release. Is there a rough time frame in which we can expect it?

**Comment by machawk1** [comment]
@milliem-3923 Not a problem. I don't expect you to have to compile the application from source to use WAIL -- that would be counter to the intention of the application.

I am _hoping_ to push a new release by the end of 2018. I can @ you on this ticket when I can verify that it's resolved if you would like.

In the meantime, per the README in this repo, we created a reimagined version of WAIL at https://github.com/n0tan3rd/wail. While this includes different capture tools than what is included here, the tools included in the re-imagining version are capable of high-fidelity web archiving using a headless browser. Feel free to check it out or stay tuned to this GitHub issue as I get it resolved.

/cc @n0tan3rd

**Comment by milliem-3923** [comment]
@machawk1 That would be great, I'll keep an eye out for it. In the meantime I'll check out the alternate version. Many thanks!

**Comment by AtLastForgot** [comment]
For what it's worth, I'm also having the same trouble that the OP mentioned. I'll keep an eye here and see if it gets resolved.

**Comment by machawk1** [comment]
@AtLastForgot Thanks for the ping on this. I have updated the code a bit since the last release, which might remedy this issue. I am working to get a new release for Windows. When this occurs, I can send out a response here to let you (and @milliem-3923) know that a new version for Windows is ready for testing.

**Comment by inkouper** [comment]
The issue remains (Windows 10 Pro, 64-bit). Is there a way to solve it by explicitly specifying the path?
![wail error](https://user-images.githubusercontent.com/6144079/161980037-dbf05993-7c6c-4062-a197-4356358fea8d.png)

**Comment by machawk1** [comment]
Hi @inkouper, it is not as straightforward as changing the paths. There is a long-standing issue with the binary (.exe) provided for Windows that is resolved in source but a new build has not been released in some time. Pings like yours here indicate to me that there is still interest, so I will work toward resolving the remaining issue and getting another release for Windows out.
